### ISSUE TITLE
[gazebo_ros_tactile] take high curvature into consideration for force distribution

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/gazebo_tactile_plugins#3]
Currently an [angle](https://github.com/ubi-agni/gazebo_tactile_plugins/blob/kinetic-devel/gazebo_ros_tactile/src/gazebo_ros_tactile.cpp#L761)  of 90 degrees between the incoming force vector and a taxel normal vectoris allowed [here](https://github.com/ubi-agni/gazebo_tactile_plugins/blob/kinetic-devel/gazebo_ros_tactile/src/gazebo_ros_tactile.cpp#L773) for distributing the force along the taxel normal.
With this system, some taxels on highly curved shapes are being activated although they are almost at 90 degrees from the applied force direction.
This is not realistic. A smaller angle threshold should be used.
No decision made yet on which angle threshold to choose.

**Comment by rhaschke** [comment]
Why use a binary decision at all? While Gazebo provides arbitrary forces (normal + shear components), the sensor can only measure the normal part. So, why not simply consider the normal part only?

**Comment by guihomework** [comment]
The problem is more subtle. 
First, we want to use the contact force with both of its components, because a force that has a shear component would actually slide the "foam" on top of the sensing MID, pulling the whole fingercap along the shear force, which will create an additional contact of the foam at another taxel as well due to the curved shape. So we kept the full force component and compute the normalscalar force at each given taxel (some will get the normal component of the gazebo force, some will get more the shear component of the force).  There is not full shear force transfer to taxels at a 90 deg angle, but definitely some closer angles should get some force. 

Second, the "binary" decision is only related to curvature, to avoid distributing the gazebo contact force to normals facing in opposite direction.

The problem I raised is that 90 degree is too large, it needs to be smaller. A full study of how it happens in reality is too much.

**Comment by guihomework** [comment]
After discussion the choice was made to use an exponential distribution for both the distance (contact center to taxel center) and the angle (contact normal to taxel normal).
An additional distribution called constant distribution, was added as well and can be selected from the urdf. It distributes the force with the same intensity on all cells within the given distance, and with the angle between contact normal and taxel normal smaller than the given angle. This distribution was requested by a team member to just have a "neighborhood" activation of taxels with same intensity (not simulating deformable foam/rubber pads)

**Comment by guihomework** [comment]
solved in melodic-devel
